import { useLocation, useNavigate } from "react-router-dom";
import { FolderKanban, ArrowUpRight } from "lucide-react";

const ProjectList = ({ projects, darkMode }) => {
  const navigate = useNavigate(); const location = useLocation();
  if (!projects.length) return <div className={`border border-dashed p-10 text-center ${darkMode ? "border-[#344055] text-slate-400" : "border-slate-300 text-slate-500"}`}><FolderKanban size={22} className="mx-auto mb-3 text-[#e66a3d]" /><p className="font-medium">No projects yet</p><p className="mt-1 text-sm">Create a project to give your work a home.</p></div>;
  return <div className="grid grid-cols-1 gap-px border border-slate-200 bg-slate-200 md:grid-cols-2 xl:grid-cols-3 dark:border-[#2a3445] dark:bg-[#2a3445]">{projects.map((project) => { const data = project.projectId; const path = `/projects/${data._id}`; const active = location.pathname.startsWith(path); return <button key={project._id} onClick={() => navigate(path)} className={`group min-h-44 p-5 text-left transition ${darkMode ? "bg-[#1a2130] hover:bg-[#202a3b]" : "bg-white hover:bg-[#fffaf8]"} ${active ? "ring-1 ring-inset ring-[#e66a3d]" : ""}`}><div className="flex items-start justify-between gap-3"><span className="grid h-8 w-8 place-items-center bg-[#fdf0eb] text-[#bd4f29]"><FolderKanban size={16} /></span><ArrowUpRight size={16} className="text-slate-300 transition group-hover:text-[#e66a3d]" /></div><h2 className={`mt-6 font-semibold ${darkMode ? "text-white" : "text-slate-900"}`}>{data.name}</h2><p className="mt-1 line-clamp-2 text-sm leading-6 text-slate-500">{data.description || "No project description"}</p><p className="mt-5 text-xs font-medium uppercase tracking-wide text-slate-400">{project.role || "member"}</p></button>; })}</div>;
};
export default ProjectList;
