import { useNavigate } from "react-router-dom";
import { ArrowRight, CheckCircle2, FolderKanban, MessageSquareText, BarChart3 } from "lucide-react";
import { motion } from "framer-motion";

const features = [[FolderKanban, "Projects", "A focused place for plans, tasks, and decisions."], [MessageSquareText, "Conversations", "Keep quick team updates close to the work."], [BarChart3, "Progress", "See what is moving without another status meeting."]];
const Home = () => {
  const navigate = useNavigate();
  return <div className="min-h-screen bg-[#f7f8fa] text-slate-900"><header className="mx-auto flex h-16 max-w-6xl items-center justify-between px-6"><button onClick={() => navigate("/")} className="flex items-center gap-2 font-semibold tracking-tight"><span className="grid h-7 w-7 place-items-center bg-[#e66a3d] text-sm text-white">S</span> Syncly</button><div className="flex items-center gap-4 text-sm"><button onClick={() => navigate("/signin")} className="font-medium text-slate-600 transition hover:text-slate-950">Sign in</button><button onClick={() => navigate("/signup")} className="bg-[#172033] px-3.5 py-2 font-medium text-white transition hover:bg-[#293247] active:scale-[.98]">Create workspace</button></div></header>
    <main className="mx-auto max-w-6xl px-6 pb-16 pt-16 lg:pt-24"><motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .42 }} className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[.12em] text-[#bd4f29]">Project coordination, without the noise</p><h1 className="mt-5 text-5xl font-semibold leading-[1.03] tracking-[-.045em] sm:text-6xl">A clearer way to run the work your team depends on.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-500">Syncly brings projects, personal tasks, and team communication into one calm, practical workspace.</p><div className="mt-9 flex flex-wrap gap-3"><button onClick={() => navigate("/signup")} className="flex items-center gap-2 bg-[#e66a3d] px-5 py-3 font-semibold text-white transition hover:bg-[#cb5630] active:scale-[.98]">Get started <ArrowRight size={17} /></button><button onClick={() => navigate("/signin")} className="border border-slate-300 bg-white px-5 py-3 font-semibold transition hover:border-slate-500">Sign in</button></div></motion.div>
      <motion.section initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .42, delay: .12 }} className="mt-16 overflow-hidden border border-slate-200 bg-white shadow-[0_16px_40px_rgba(20,27,42,.06)]"><div className="grid border-b border-slate-200 sm:grid-cols-3">{[["12", "Active projects"], ["38", "Open tasks"], ["84%", "Weekly delivery"]].map(([value, label]) => <div key={label} className="border-b border-slate-200 p-5 last:border-b-0 sm:border-b-0 sm:border-r sm:last:border-r-0"><p className="text-2xl font-semibold">{value}</p><p className="mt-1 text-sm text-slate-500">{label}</p></div>)}</div><div className="grid gap-px bg-slate-200 md:grid-cols-3">{features.map(([Icon, name, text]) => <div key={name} className="bg-white p-6"><Icon size={19} className="text-[#e66a3d]" /><h2 className="mt-5 font-semibold">{name}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></div>)}</div></motion.section>
      <div className="mt-10 flex items-center gap-2 text-sm text-slate-500"><CheckCircle2 size={16} className="text-emerald-600" /> Built for focused teams who prefer progress over process.</div>
    </main></div>;
};
export default Home;
